version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"    # Web interface
      - "2055:2055/udp" # NetFlow
      - "6343:6343/udp" # sFlow
    environment:
      - DATABASE_URL=postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}
      - SESSION_SECRET=${SESSION_SECRET:-defaultsecretkey}
      - FLOW_RETENTION_DAYS=${FLOW_RETENTION_DAYS:-7}
      - USE_EXTERNAL_STORAGE=${USE_EXTERNAL_STORAGE:-false}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio:9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-}
      - MINIO_BUCKET=${MINIO_BUCKET:-r369-bucket}
      - MINIO_SECURE=${MINIO_SECURE:-false}
      - TZ=${TZ:-UTC}
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Provide extra host network capacity for flow processing
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 65535
        hard: 65535

  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGUSER:-flowvision}
      - POSTGRES_PASSWORD=${PGPASSWORD:-flowvisionpass}
      - POSTGRES_DB=${PGDATABASE:-flowvision}
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER:-flowvision}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Optional MinIO service for external storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  postgres_data:
  minio_data:
